### ISSUE TITLE
Icons for search results

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RGD-Vue#23]
See if the UI/UX team can help generate some icons for the following data types:

- Raster: geospatial imagery
- ImageSetSpatial: a group of images
- Geometry: vector geometry/shape
- SpatialAsset: group of arbitrary files
- Mesh3DSpatial: a 3D mesh
- FMV: full motion video (overhead video)

**Comment by marySalvi** [comment]
@banesullivan  did you say there were icons currently in use somewhere or am I remembering that incorrectly?

**Comment by banesullivan** [comment]
Nope, no current icons - we'll need the UI/UX team to create some or find some icons we can use without restriction

**Comment by marySalvi** [comment]
Ok, good to know. Thanks
