### ISSUE TITLE
Unauthenticated Search error

### ISSUE THREAD

**Issue by annehaley** [ResonantGeoData/RGD-Vue#26]
If the user is unauthenticated, hitting the Search button appears to do nothing because the search request fails with 401. We can either display this message to the user in a snackbar or enforce that a user must be authenticated to reach the search page.

**Comment by banesullivan** [comment]
IMO, they shouldn't be able to access the app at all if not authenticated. Perhaps a pop up forcing them to log in could prevent them from interacting with the other components?
