### ISSUE TITLE
Create Processed image dropdown

### ISSUE THREAD

**Issue by marySalvi** [ResonantGeoData/RGD-Vue#34]
drop down will appear on raster page 

depends on #34

**Comment by banesullivan** [comment]
Which issue does this depend on?

The UI for this could get rather complex. @marySalvi, I'd like to be involved when this work is started and being designed. I'm hoping that we can do a side-by-side style view with processed images using a split view in CesiumJS like https://sandcastle.cesium.com/?src=Imagery%20Layers%20Split.html

**Comment by marySalvi** [comment]
My apologies @banesullivan , depends on #39 , updated original description. I am hoping to have something up today for #39 and we can work from there and meet if necessary
