### ISSUE TITLE
Footprints error

### ISSUE THREAD

**Issue by annehaley** [ResonantGeoData/RGD-Vue#37]
When a default search is performed (predicate=intersects) with no area specified, `main` now raises the following server-side error:

```
AssertionError: Cannot both declare the field  'footprint' and include it in the SpatialEntryFootprintSerializer 'exclude' option.  Remove the field or, if inherited from a parent  serializer, disable with `footprint = None`
```

**Comment by banesullivan** [comment]
This should have been fixed

**Comment by annehaley** [comment]
My mistake, I simply needed to pull the backend! I keep forgetting that the progress on these repos is mutally exclusive
