### ISSUE TITLE
Create Raster View

### ISSUE THREAD

**Issue by marySalvi** [ResonantGeoData/RGD-Vue#39]
Raster View should be modeled to have the same data as on the current [SSR Site](https://www.resonantgeodata.com/rgd_imagery/raster/1/) but designed with current style guidelines. Components needed for the view are:
(Starred components exist)
- [ ] Toolbar* 
   - [x] Raster Title
   - [x] Created date
   - [x] Modified date
   - [x] Acquired date
   - [x] Return to Search Button*
   - [ ] Copy GeoJson Button

- [ ] SideBar*
     - [x] DataTable to display Raster File Details*
     - [x] Image and Band Selectors
     - [x] Raster Layer Opacity Slider
     - [ ] Raster Thumbnail
- [ ] Cesium Viewer*
     - [x] BaseMap Selector*
     - [ ] Draw ROI Tool
          - [ ] Draw ROI Button
          - [ ] Download Button
          - [ ] Clear Button

extension of #25

**Comment by banesullivan** [comment]
Hold off on the ROI tool for now to make progress on the rest
