### ISSUE TITLE
add tile toggle to results table

### ISSUE THREAD

**Issue by marySalvi** [ResonantGeoData/RGD-Vue#48]
add eye icon to results table that toggles tiling for each raster. Should be able to select multiple results

Does not need to be a new component but does need to update a value in store so that it is accessible by the cesiumViewer

**Comment by banesullivan** [comment]
I suppose the way to implement this will be having a callback `setVisibility(state)` that has a switch statement for each type:

```
case "Raster":
   showOrHideTiles
case "3D Tiles":
   showOrHideData
etc...
```
