### ISSUE TITLE
focused data component

### ISSUE THREAD

**Issue by marySalvi** [ResonantGeoData/RGD-Vue#49]
When a row is selected in the results table the 'focused data' component should populate below the results table.

Component should be a molecule and should include:

- image dropdown
- band dropdown
- opacity slider
- icon to zoom to selected raster

**Comment by banesullivan** [comment]
There should be a general/abstract implementation for all SpatialEntry types that has the icon to zoom to it's footprint.

The raster sub type will have the image dropdown, opacity slider, etc
