### ISSUE TITLE
Tiling not working

### ISSUE THREAD

**Issue by marySalvi** [ResonantGeoData/RGD-Vue#73]
Tiling is not currently working on live site. Console gives the following error:
![Screenshot from 2022-01-17 11-42-55](https://user-images.githubusercontent.com/40494088/149809082-b540fcda-e0d0-4ed6-a26e-727dc29f937e.png)

**Comment by banesullivan** [comment]
Update RGD - see https://github.com/ResonantGeoData/RGD-Vue/pull/55

This requires https://github.com/ResonantGeoData/ResonantGeoData/commit/7aac4d58c8277e3782ce68273d8cfa3b7c6f354f

**Comment by banesullivan** [comment]
Reopening as you mentioned this is for the production site. I will update the production server

**Comment by banesullivan** [comment]
Updated the RD-OpenGeo production deployment and this is now working
