### ISSUE TITLE
Fix failing CI

### ISSUE THREAD

**Issue by annehaley** [ResonantGeoData/RGD-Vue#76]
We should fix all the style errors causing CI failures before we fork to the WATCH repo.

**Comment by banesullivan** [comment]
Can we ignore all warnings we don't care about, e.g., line length?

**Comment by annehaley** [comment]
Are you sure we should? Following those rules does increase readability, and making a few tiny changes now is far easier than a huge code cleanup later.

**Comment by banesullivan** [comment]
Fair enough - can you make sure `yarn lint --no-fix` fails on `warning`s then?

IMO, the max line length should be allowed up to `100`... FYI, I don't think this is currently failing on CI so line length kind of a tangent 🙃

**Comment by banesullivan** [comment]
Personally, I'd like to see the CI steps as:

1. Check for errors: `yarn lint --no-fix | grep "error:"`
2. Check for warnings: `yarn lint --no-fix --max-warnings 0`

**Comment by annehaley** [comment]
Made this change in #77 to help us tackle this issue

**Comment by annehaley** [comment]
@banesullivan After merging, I actually found that using grep in the CI command caused failures every time at that line. I'm not sure why this line consistently failed, as it gave no further information: https://github.com/ResonantGeoData/RGD-Vue/runs/4847877741?check_suite_focus=true
